x-base: &base
  image: crux_climbing
  build: .
  volumes:
    - .:/app
  env_file:
    - .env

services:
  web:
    <<: *base
    command: ./bin/rails server -b '0.0.0.0' -p 3000
    container_name: crux_climbing_web
    networks:
      - crux_climbing
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    container_name: crux_climbing_db
    image: postgres:16
    networks:
      - crux_climbing
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
      - .:/app
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password

networks:
  crux_climbing:
